### PR TITLE
update readmes

### PR DESCRIPTION
**Pull request by nyakotey**

### CODE REVIEW

**Comment by RDjarbeng** [comment]
You can say 'added the black theme', 'introduced black theme 🖤'  instead of plenty words. 😏

**Review by RDjarbeng — CHANGES_REQUESTED** [review]
I see the potential changes/upcoming features did not feature a  screenshot from #91 showing the countdown without clicking 😕

**Comment by nyakotey** [comment]
> I see the potential changes/upcoming features did not feature a screenshot from #91 showing the countdown without clicking confused

Do revise your comment, it does not convey any meaning that is worth acting upon

**Review by RDjarbeng — APPROVED** [review]
Looks good, you may merge

**Pull request merged**
