### PR TITLE
Fix Update On Elapsed on listpage

### PR DESCRIPTION
**Pull request by RDjarbeng**
When countdown elapses the text updates but the text and  icon remains green, added a refresh of the list when it elapses instead

### CODE REVIEW

**Comment by RDjarbeng** [comment]
Also removed unncessary await from displayCountdowns and changed syntax .then() to use normal try and catch

**Review by nyakotey — CHANGES_REQUESTED** [review]
Well this `PR` just made me discover bugs that are currently in master, which seems to be worse in this PR.
Please check the live updating of countdowns

**Comment by RDjarbeng** [comment]
Added some changes to fix issues, after small refactor 🙂

**Review by nyakotey — APPROVED** [review]

**Comment by RDjarbeng** [comment]
Solved quite a number of bugs with this PR

**Pull request merged**
