### PR TITLE
v2 beta

### LINKED ISSUE #28: Make site exciting to watch
Add animations, transitions (not too much) to make clock interesting to watch

### LINKED ISSUE #41: enable theme persistence  site/app wide
add a way to remember theme choices #40

### LINKED ISSUE #57: Night mode does not remain consistent across pages
The night mode state does not remain consistent across the site even when the user toggles it. The auto night mode changes the night mode state even when the user picks a specific one.

### PR DESCRIPTION
**Pull request by nyakotey**
add a cool sidebar, redesign ui, improve responsiveness,
customizable theme + mode!
remove old svg, redundant comments

resolve #57
resolve #41
resolve #28

### CODE REVIEW

**Comment by RDjarbeng** [comment]
Maybe shift the pink theme color button to the right of the red (between red and yellow). Just so it has a rainbow feel

**Review by RDjarbeng — CHANGES_REQUESTED** [review]
Once the broken links are resolved I think we can merge this pull request.
I have also completed the custom countdown in #39 with that sorta animated countdown so the pencil icon part can start working once we merge the two.
Hopefully no breaking changes

**Comment by nyakotey** [comment]
> Maybe shift the pink theme color button to the right of the red (between red and yellow). Just so it has a rainbow feel

done

**Comment by nyakotey** [comment]
> Once the broken links are resolved I think we can merge this pull request. I have also completed the custom countdown in #39 with that sorta animated countdown so the pencil icon part can start working once we merge the two. Hopefully no breaking changes

about the broken links, do you mean until those features are implemented?

**Review by nyakotey — COMMENTED** [review]
* moved the pink ico in between red and yellow

**Comment by RDjarbeng** [comment]
> about the broken links, do you mean until those features are implemented?

You could remove those links before you merge into master so that only the implemented/working ones are on the live site

**Comment by nyakotey** [comment]
> > * moved the pink ico in between red and yellow
> 
> where can't see it on my side image

clear cache and try again :)

**Comment by nyakotey** [comment]
> You could remove those links before you merge into master so that only the implemented/working ones are on the live site

@RDjarbeng 
No, if it must be done, then there shall be no merging until it's complete! 
sidenote: I'm not going to accept a version other v2 after all this, cos these are significant updates.

**Comment by nyakotey** [comment]
implement #41

**Comment by RDjarbeng** [comment]
About the custom backgrounds I think we can set some default backgrounds for the user to use and nit rely in user uploading one. This is also good incase the user's background is not showing correctly.
Change the 'upload... Background' to 'set background'

**Comment by RDjarbeng** [comment]
> Date time picker, Set the date time picker so dates that are less than the next day (the day after the countdown, tomorrow) are invalid. Otherwise the user will see a static clock with zeros. Also the current day is not allowed because only dates are selected, default is midnight. This will remain until the user can set their own time

Fixed it myself

**Comment by RDjarbeng** [comment]
Will use this pull request as a final launch pad for v2.0.0 once #46 is done

**Comment by nyakotey** [comment]
Everything's set! :1st_place_medal:

**Comment by RDjarbeng** [comment]
Not on  the service worker it ain't

**Review by RDjarbeng — COMMENTED** [review]
Needs to be updated with service worker 👷.
Waiting for beta testers to finalize and launch on 1st April

**Review by RDjarbeng — APPROVED** [review]
Everything looks good now

**Comment by RDjarbeng** [comment]
At long last

**Pull request merged**
