### PR TITLE
Customizable

### PR DESCRIPTION
**Pull request by RDjarbeng**
Added the custom date input functionality, yet to add better UI functionality in a list.
Hopefully it looks better than it does now

### CODE REVIEW

**Comment by RDjarbeng** [comment]
Please just take a look. (Be merciful) I've run into issues with the datetime picker, wanted it to be date and time, but currently only supports dates. But at least the bottom countdown works,  just have to decide on some things

**Comment by nyakotey** [comment]
@RDjarbeng I don't know what to make of it:
1. First what's up with the 2nd clock row? Does that mean if the user enters say 4 countdown dates there will be 5(including the new Year one) clock rows on the page?
>yet to add better UI functionality in a list

alright

2. with the datetime picker it works, however it does not countdown. 
> But at least the bottom countdown works...

unfortunately it doesn't, it can only be set

&#128542;&#128542;&#128542; I'm afraid this PR is not mergeable quite yet &#128542;&#128542;&#128542;

**Review by nyakotey — CHANGES_REQUESTED** [review]
@RDjarbeng I don't know what to make of it:
1. First what's up with the 2nd clock row? Does that mean if the user enters say 4 countdown dates there will be 5(including the new Year one) clock rows on the page?
>yet to add better UI functionality in a list

alright

2. with the datetime picker it works, however it does not countdown. 
> But at least the bottom countdown works...

unfortunately it doesn't, it can only be set

&#128542;&#128542;&#128542; I'm afraid this PR is not mergeable quite yet &#128542;&#128542;&#128542;

**Comment by RDjarbeng** [comment]
What do you mean the date time picker works?
I tried.
Or you added new code?

**Comment by RDjarbeng** [comment]
What do you mean the date time works?
I tried only date works, there was no time ⌚ component.
Or you added new code?

**Comment by nyakotey** [comment]
> What do you mean the date time works? I tried only date works, there was no time watch component. Or you added new code?

no, I haven't added anything. oh ok I thought you were not aware that the 2nd timer doesn't count down. my bad

**Comment by RDjarbeng** [comment]
What do you think now @nyakotey ?

**Comment by RDjarbeng** [comment]
I added an interval of 7 to the day count because it takes long to complete for large day intervals. It's a patch but it works fine 💯

**Comment by RDjarbeng** [comment]
I'll have to work on the merge conflicts later for now take a look

**Review by nyakotey — COMMENTED** [review]
@RDjarbeng looks good.
Don't merge it though, we've not discussed storing the custom countdowns + creating a new html file as you suggested sometime ago

**Comment by RDjarbeng** [comment]
The 'creating a new html file' part will have to go for a different
version. For now I'm looking at the local storage part alone

**Review by nyakotey — COMMENTED** [review]
good

**Pull request merged**
