### PR TITLE
bugfix for #128

### PR DESCRIPTION
**Pull request by abhishekm2106**

### CODE REVIEW

**Comment by abhishekm2106** [comment]
just saw that a pr for this already exists

**Comment by RDjarbeng** [comment]
You can keep it open, just because a PR exists doesn't mean you should be discouraged.

@abhishekm2106  can you fix the bug for the send to WhatsApp as well.

I've looked at your implementation.

**Comment by RDjarbeng** [comment]
Screenshot of the current behaviour when the whatsapp icon button is clicked:

image

As you can see it should show '../366' and it's still using the hardcoded value

**Comment by RDjarbeng** [comment]
Issue in #133.

@abhishekm2106 You can work on that as part of this PR. That is if you are interested

**Review by RDjarbeng — APPROVED** [review]

**Review by nyakotey — APPROVED** [review]

**Comment by RDjarbeng** [comment]
Closes #128

**Pull request merged**
