### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by nyakotey**

### CODE REVIEW

**Comment by RDjarbeng** [comment]
So should I close the documentation readme pull request #80 ?

**Comment by RDjarbeng** [comment]
Nice with the images showing all the themes

**Comment by nyakotey** [comment]
> So should I close the documentation readme pull request #80 ?

yeah, but not to delete that branch, it will be going into the docs folder

**Comment by nyakotey** [comment]
> Nice with the images showing all the themes

yep, was very intentional 😉

**Pull request merged**
